
version: "3.6"
services:
  db:
    image: postgres:alpine
    restart: on-failure:10
    volumes:
      - ${USERDIR}/postgres/data:/var/lib/postgresql/data
  app:
    image: nextcloud:fpm-alpine
    restart: on-failure:10
    volumes:
      - ${USERDIR}/nextcloud:/var/www/html
    environment:
      VIRTUAL_HOST: www.nextcloud.hoho.eu.org,nextcloud.hoho.eu.org
      LETSENCRYPT_HOST: www.nextcloud.hoho.eu.org,nextcloud.hoho.eu.org
      LETSENCRYPT_EMAIL: tonibobone@gmail.com
      POSTGRES_HOST: db
      POSTGRES_PASSWORD:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud

networks:
  default:
    external:
      name: webproxy
