
version: "3.6"
services:
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      TRANSMISSION_WEB_HOME: /combustion-release/
      USER: ${ADMIN_USERNAME}
      PASS: ${ADMIN_PASSWORD}
      VIRTUAL_HOST: trans.${VIRTUAL_HOST}
      LETSENCRYPT_HOST: trans.${VIRTUAL_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/transmission/config:/config
      - ${USERDIR}/transmission/watch:/data/watch
      - ${USERDIR}/transmission/downloads:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: on-failure:5
networks:
  default:
    external:
      name: webproxy